#!/bin/csh
#
#       $Id: run,v 1.1 1999/01/27 00:43:42 mike Exp $
#
set cmd=vsix
while ( $#argv > 1 )
	set cmd = ( $cmd $argv[1] )
	shift argv
end
set no=`vsinput $argv[1]` && exec $cmd $no
echo $no
#
#       $Log: run,v $
#       Revision 1.1  1999/01/27 00:43:42  mike
#       Initial revision
#
#
