#!/bin/sh
cmd=./vsix
while [ $# -gt 1 ]; do
        cmd="$cmd $1"
        shift
done
echo will run $cmd
no=`./vsinput $1` && exec $cmd $no
echo $no
#
#       $Log: run,v $
#       Revision 1.2  2001/02/17 03:41:28  mike
#       Merge with dvv (who sometimes poses as root) and leob.
#
#       Revision 1.1.1.1  2001/02/01 03:48:39  root
#       e50 and -Wall fixes
#
#       Revision 1.2  2001/01/31 22:58:43  dvv
#       fixes to for whetstone and -Wall
#
#       Revision 1.1  1999/01/27 00:43:42  mike
#       Initial revision
#
#
